name: Create custom AMI

on:
    release:
        types: [published]
    workflow_dispatch:

env:
    PACKER_VERSION: "1.11.2"

permissions:
    id-token: write
    contents: read

jobs:
    build_ami:
        name: build ami using packer
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout Repo
            - name: Checkout Repo
              uses: actions/checkout@v4

            # Step 2: Install packer
            - name: Setup packer
              uses: hashicorp/setup-packer@main
              with:
                version: ${{ env.PACKER_VERSION }}
            
            # Step 3: Init Packer
            - name: Init Packer
              run: "packer init ./ec2-instance.pkr.hcl"

            # Step 4: Save variables in script
            - name: Create and save bash script
              run: |
                sudo cat > secrets.sh <<EOF
                export SECRET_KEY='${{ secrets.SECRET_KEY }}'
                export DB_USER='${{ secrets.DB_USER }}'
                export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
                EOF

            # Step 5: Setup AWS Creds
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                audience: sts.amazonaws.com
                role-to-assume: arn:aws:iam::762233724830:role/GitHubActions-mvp
                aws-region: eu-west-1
            
            # Step 6: Packer Build
            - name: Packer build
              run: packer build -on-error=abort -var "vpc_id=${{ secrets.VPC_ID }}" -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "version=${{ github.ref_name }}" ./ec2-instance.pkr.hcl